### ISSUE TITLE
No option in Matsuri

### ISSUE THREAD

**Issue by wulfric93** [uoosef/nekobepass#5]
![image](https://github.com/uoosef/nekobepass/assets/117269334/0588222e-faa8-4849-baad-cfed0c57c640)
hi there hope you doing well 
i've installed this plugin but nothing shows at advanced plugin section

**Comment by DanielcoderX** [comment]
Hello.
- First: thanks for your interest in using _bepass_.
- Second: You have to use in NekoBox, after installing the plugin, you must go to NekoBox --> settings --> plugins and then enabled the Bepass plugin. After that you can easily implement your own config

**Comment by wulfric93** [comment]
your wellcome brother 
but how can i use it ?

**Comment by DanielcoderX** [comment]
You can just click on plus icon on top-right and then click on _Advanced plugin_ and then select bepass
I'm going to work on wiki ASAP.
